// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFluxACredential = `-- name: GetFluxACredential :one
SELECT user_id, site, token_ciphertext, created_at, updated_at
FROM fluxa_credentials
WHERE user_id = $1 AND site = $2
`

type GetFluxACredentialParams struct {
	UserID string
	Site   string
}

func (q *Queries) GetFluxACredential(ctx context.Context, arg GetFluxACredentialParams) (FluxaCredential, error) {
	row := q.db.QueryRow(ctx, getFluxACredential, arg.UserID, arg.Site)
	var i FluxaCredential
	err := row.Scan(
		&i.UserID,
		&i.Site,
		&i.TokenCiphertext,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuthIdentity = `-- name: GetUserByAuthIdentity :one
SELECT u.id, u.username, u.display_name, u.email, u.avatar_url, u.password_hash, u.created_at
FROM auth_identities ai
JOIN users u ON u.id = ai.user_id
WHERE ai.provider = $1 AND ai.provider_subject = $2
`

type GetUserByAuthIdentityParams struct {
	Provider        string
	ProviderSubject string
}

type GetUserByAuthIdentityRow struct {
	ID           string
	Username     string
	DisplayName  string
	Email        string
	AvatarUrl    string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByAuthIdentity(ctx context.Context, arg GetUserByAuthIdentityParams) (GetUserByAuthIdentityRow, error) {
	row := q.db.QueryRow(ctx, getUserByAuthIdentity, arg.Provider, arg.ProviderSubject)
	var i GetUserByAuthIdentityRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, email, avatar_url, password_hash, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           string
	Username     string
	DisplayName  string
	Email        string
	AvatarUrl    string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, email, avatar_url, password_hash, created_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           string
	Username     string
	DisplayName  string
	Email        string
	AvatarUrl    string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAuthIdentity = `-- name: UpsertAuthIdentity :execrows
INSERT INTO auth_identities (
	id, user_id, provider, provider_subject, email, email_verified, avatar_url, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (provider, provider_subject) DO UPDATE SET
	user_id = EXCLUDED.user_id,
	email = EXCLUDED.email,
	email_verified = EXCLUDED.email_verified,
	avatar_url = EXCLUDED.avatar_url,
	updated_at = EXCLUDED.updated_at
`

type UpsertAuthIdentityParams struct {
	ID              string
	UserID          string
	Provider        string
	ProviderSubject string
	Email           string
	EmailVerified   bool
	AvatarUrl       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertAuthIdentity(ctx context.Context, arg UpsertAuthIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.EmailVerified,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertFluxACredential = `-- name: UpsertFluxACredential :execrows
INSERT INTO fluxa_credentials (user_id, site, token_ciphertext, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, site) DO UPDATE SET
	token_ciphertext = EXCLUDED.token_ciphertext,
	updated_at = EXCLUDED.updated_at
`

type UpsertFluxACredentialParams struct {
	UserID          string
	Site            string
	TokenCiphertext string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertFluxACredential(ctx context.Context, arg UpsertFluxACredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertFluxACredential,
		arg.UserID,
		arg.Site,
		arg.TokenCiphertext,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertUser = `-- name: UpsertUser :execrows
INSERT INTO users (id, username, display_name, email, avatar_url, password_hash, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
	username = EXCLUDED.username,
	display_name = EXCLUDED.display_name,
	email = EXCLUDED.email,
	avatar_url = EXCLUDED.avatar_url,
	password_hash = EXCLUDED.password_hash
`

type UpsertUserParams struct {
	ID           string
	Username     string
	DisplayName  string
	Email        string
	AvatarUrl    string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
