// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSelectedUserChatModels = `-- name: CountSelectedUserChatModels :one
SELECT COUNT(*)
FROM user_chat_models
WHERE user_id = $1 AND purpose = $2 AND is_selected = TRUE
`

type CountSelectedUserChatModelsParams struct {
	UserID  string
	Purpose string
}

func (q *Queries) CountSelectedUserChatModels(ctx context.Context, arg CountSelectedUserChatModelsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSelectedUserChatModels, arg.UserID, arg.Purpose)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatSession = `-- name: CreateChatSession :execrows
INSERT INTO chat_sessions (id, user_id, title, pinned, last_message_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateChatSessionParams struct {
	ID            string
	UserID        string
	Title         string
	Pinned        bool
	LastMessageAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createChatSession,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Pinned,
		arg.LastMessageAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSession = `-- name: CreateSession :execrows
INSERT INTO sessions (id, user_id, access_token, refresh_token, expires_at, revoked_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSessionParams struct {
	ID           string
	UserID       string
	AccessToken  string
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUserChatModel = `-- name: CreateUserChatModel :execrows
INSERT INTO user_chat_models (id, user_id, purpose, origin, name, base_url, api_key_encrypted, model_name, temperature, is_selected, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateUserChatModelParams struct {
	ID              string
	UserID          string
	Purpose         string
	Origin          string
	Name            string
	BaseUrl         string
	ApiKeyEncrypted string
	ModelName       string
	Temperature     float64
	IsSelected      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateUserChatModel(ctx context.Context, arg CreateUserChatModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, createUserChatModel,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.Origin,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.ModelName,
		arg.Temperature,
		arg.IsSelected,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatMessageSources = `-- name: DeleteChatMessageSources :execrows
DELETE FROM chat_message_sources
WHERE message_id = $1
`

func (q *Queries) DeleteChatMessageSources(ctx context.Context, messageID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatMessageSources, messageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatSession = `-- name: DeleteChatSession :execrows
DELETE FROM chat_sessions
WHERE id = $1 AND user_id = $2
`

type DeleteChatSessionParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteChatSession(ctx context.Context, arg DeleteChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserChatModel = `-- name: DeleteUserChatModel :execrows
DELETE FROM user_chat_models
WHERE id = $1 AND user_id = $2
`

type DeleteUserChatModelParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteUserChatModel(ctx context.Context, arg DeleteUserChatModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserChatModel, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureUserChatModelDefault = `-- name: EnsureUserChatModelDefault :execrows
INSERT INTO user_chat_models (id, user_id, purpose, origin, name, base_url, api_key_encrypted, model_name, temperature, is_selected, created_at, updated_at)
SELECT $1, $2, $3, 'default', $4, $5, $6, $7, $8, TRUE, $9, $9
WHERE NOT EXISTS (
	SELECT 1 FROM user_chat_models WHERE user_id = $2 AND purpose = $3
)
`

type EnsureUserChatModelDefaultParams struct {
	ID              string
	UserID          string
	Purpose         string
	Name            string
	BaseUrl         string
	ApiKeyEncrypted string
	ModelName       string
	Temperature     float64
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) EnsureUserChatModelDefault(ctx context.Context, arg EnsureUserChatModelDefaultParams) (int64, error) {
	result, err := q.db.Exec(ctx, ensureUserChatModelDefault,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.ModelName,
		arg.Temperature,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, user_id, title, pinned, last_message_at, created_at, updated_at
FROM chat_sessions
WHERE id = $1 AND user_id = $2
`

type GetChatSessionParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetChatSession(ctx context.Context, arg GetChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Pinned,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSelectedUserChatModel = `-- name: GetSelectedUserChatModel :one
SELECT id, user_id, purpose, origin, name, base_url, api_key_encrypted, model_name, temperature, is_selected, created_at, updated_at
FROM user_chat_models
WHERE user_id = $1 AND purpose = $2 AND is_selected = TRUE
LIMIT 1
`

type GetSelectedUserChatModelParams struct {
	UserID  string
	Purpose string
}

type GetSelectedUserChatModelRow struct {
	ID              string
	UserID          string
	Purpose         string
	Origin          string
	Name            string
	BaseUrl         string
	ApiKeyEncrypted string
	ModelName       string
	Temperature     float64
	IsSelected      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetSelectedUserChatModel(ctx context.Context, arg GetSelectedUserChatModelParams) (GetSelectedUserChatModelRow, error) {
	row := q.db.QueryRow(ctx, getSelectedUserChatModel, arg.UserID, arg.Purpose)
	var i GetSelectedUserChatModelRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Origin,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.ModelName,
		&i.Temperature,
		&i.IsSelected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, access_token, refresh_token, expires_at, revoked_at, created_at
FROM sessions
WHERE refresh_token = $1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByAccessToken = `-- name: GetSessionByAccessToken :one
SELECT id, user_id, access_token, refresh_token, expires_at, revoked_at, created_at
FROM sessions
WHERE access_token = $1
`

func (q *Queries) GetSessionByAccessToken(ctx context.Context, accessToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByAccessToken, accessToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserChatModel = `-- name: GetUserChatModel :one
SELECT id, user_id, purpose, origin, name, base_url, api_key_encrypted, model_name, temperature, is_selected, created_at, updated_at
FROM user_chat_models
WHERE id = $1 AND user_id = $2
`

type GetUserChatModelParams struct {
	ID     string
	UserID string
}

type GetUserChatModelRow struct {
	ID              string
	UserID          string
	Purpose         string
	Origin          string
	Name            string
	BaseUrl         string
	ApiKeyEncrypted string
	ModelName       string
	Temperature     float64
	IsSelected      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserChatModel(ctx context.Context, arg GetUserChatModelParams) (GetUserChatModelRow, error) {
	row := q.db.QueryRow(ctx, getUserChatModel, arg.ID, arg.UserID)
	var i GetUserChatModelRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Origin,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.ModelName,
		&i.Temperature,
		&i.IsSelected,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChatMessageSource = `-- name: InsertChatMessageSource :execrows
INSERT INTO chat_message_sources (
	id, message_id, provider, connection_id, document_id, chunk_id,
	title, repo, url, snippet, matched_lines_json, score, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertChatMessageSourceParams struct {
	ID               string
	MessageID        string
	Provider         string
	ConnectionID     string
	DocumentID       string
	ChunkID          string
	Title            string
	Repo             string
	Url              string
	Snippet          string
	MatchedLinesJson string
	Score            float64
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertChatMessageSource(ctx context.Context, arg InsertChatMessageSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertChatMessageSource,
		arg.ID,
		arg.MessageID,
		arg.Provider,
		arg.ConnectionID,
		arg.DocumentID,
		arg.ChunkID,
		arg.Title,
		arg.Repo,
		arg.Url,
		arg.Snippet,
		arg.MatchedLinesJson,
		arg.Score,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAlternativeUserChatModels = `-- name: ListAlternativeUserChatModels :many
SELECT id, user_id, purpose, origin, name, base_url, api_key_encrypted, model_name, temperature, is_selected, created_at, updated_at
FROM user_chat_models
WHERE user_id = $1 AND purpose = $2 AND id <> $3
ORDER BY created_at ASC, name ASC
`

type ListAlternativeUserChatModelsParams struct {
	UserID  string
	Purpose string
	ID      string
}

type ListAlternativeUserChatModelsRow struct {
	ID              string
	UserID          string
	Purpose         string
	Origin          string
	Name            string
	BaseUrl         string
	ApiKeyEncrypted string
	ModelName       string
	Temperature     float64
	IsSelected      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListAlternativeUserChatModels(ctx context.Context, arg ListAlternativeUserChatModelsParams) ([]ListAlternativeUserChatModelsRow, error) {
	rows, err := q.db.Query(ctx, listAlternativeUserChatModels, arg.UserID, arg.Purpose, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlternativeUserChatModelsRow
	for rows.Next() {
		var i ListAlternativeUserChatModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Purpose,
			&i.Origin,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEncrypted,
			&i.ModelName,
			&i.Temperature,
			&i.IsSelected,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessageSources = `-- name: ListChatMessageSources :many
SELECT id, message_id, provider, connection_id, document_id, chunk_id,
       title, repo, url, snippet, matched_lines_json, score, created_at
FROM chat_message_sources
WHERE message_id = $1
ORDER BY created_at ASC
`

type ListChatMessageSourcesRow struct {
	ID               string
	MessageID        string
	Provider         string
	ConnectionID     string
	DocumentID       string
	ChunkID          string
	Title            string
	Repo             string
	Url              string
	Snippet          string
	MatchedLinesJson string
	Score            float64
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListChatMessageSources(ctx context.Context, messageID string) ([]ListChatMessageSourcesRow, error) {
	rows, err := q.db.Query(ctx, listChatMessageSources, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessageSourcesRow
	for rows.Next() {
		var i ListChatMessageSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Provider,
			&i.ConnectionID,
			&i.DocumentID,
			&i.ChunkID,
			&i.Title,
			&i.Repo,
			&i.Url,
			&i.Snippet,
			&i.MatchedLinesJson,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT cm.id, cm.session_id, cm.user_id, cm.role, cm.content, cm.skill, cm.use_knowledge,
       cm.prompt_tokens, cm.completion_tokens, cm.total_tokens, cm.created_at, cm.completed_at
FROM chat_messages cm
INNER JOIN chat_sessions cs ON cs.id = cm.session_id
WHERE cm.session_id = $1 AND cs.user_id = $2
ORDER BY cm.created_at ASC
`

type ListChatMessagesParams struct {
	SessionID string
	UserID    string
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages, arg.SessionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.Skill,
			&i.UseKnowledge,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatSessions = `-- name: ListChatSessions :many
SELECT id, user_id, title, pinned, last_message_at, created_at, updated_at
FROM chat_sessions
WHERE user_id = $1
ORDER BY pinned DESC, COALESCE(last_message_at, created_at) DESC, updated_at DESC
`

func (q *Queries) ListChatSessions(ctx context.Context, userID string) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listChatSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSession
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Pinned,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChatModels = `-- name: ListUserChatModels :many
SELECT id, user_id, purpose, origin, name, base_url, api_key_encrypted, model_name, temperature, is_selected, created_at, updated_at
FROM user_chat_models
WHERE user_id = $1
ORDER BY purpose ASC, is_selected DESC, created_at ASC, name ASC
`

type ListUserChatModelsRow struct {
	ID              string
	UserID          string
	Purpose         string
	Origin          string
	Name            string
	BaseUrl         string
	ApiKeyEncrypted string
	ModelName       string
	Temperature     float64
	IsSelected      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListUserChatModels(ctx context.Context, userID string) ([]ListUserChatModelsRow, error) {
	rows, err := q.db.Query(ctx, listUserChatModels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserChatModelsRow
	for rows.Next() {
		var i ListUserChatModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Purpose,
			&i.Origin,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEncrypted,
			&i.ModelName,
			&i.Temperature,
			&i.IsSelected,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveChatMessage = `-- name: SaveChatMessage :execrows
INSERT INTO chat_messages (
	id, session_id, user_id, role, content, skill, use_knowledge,
	prompt_tokens, completion_tokens, total_tokens, created_at, completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO UPDATE SET
	session_id = EXCLUDED.session_id,
	user_id = EXCLUDED.user_id,
	role = EXCLUDED.role,
	content = EXCLUDED.content,
	skill = EXCLUDED.skill,
	use_knowledge = EXCLUDED.use_knowledge,
	prompt_tokens = EXCLUDED.prompt_tokens,
	completion_tokens = EXCLUDED.completion_tokens,
	total_tokens = EXCLUDED.total_tokens,
	created_at = EXCLUDED.created_at,
	completed_at = EXCLUDED.completed_at
`

type SaveChatMessageParams struct {
	ID               string
	SessionID        string
	UserID           string
	Role             string
	Content          string
	Skill            string
	UseKnowledge     bool
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	CreatedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}

func (q *Queries) SaveChatMessage(ctx context.Context, arg SaveChatMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveChatMessage,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.Skill,
		arg.UseKnowledge,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectFallbackUserChatModel = `-- name: SelectFallbackUserChatModel :one
SELECT id
FROM user_chat_models
WHERE user_id = $1 AND purpose = $2
ORDER BY created_at ASC, name ASC
LIMIT 1
`

type SelectFallbackUserChatModelParams struct {
	UserID  string
	Purpose string
}

func (q *Queries) SelectFallbackUserChatModel(ctx context.Context, arg SelectFallbackUserChatModelParams) (string, error) {
	row := q.db.QueryRow(ctx, selectFallbackUserChatModel, arg.UserID, arg.Purpose)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setSelectedUserChatModel = `-- name: SetSelectedUserChatModel :execrows
UPDATE user_chat_models
SET is_selected = TRUE,
    updated_at = $4
WHERE user_id = $1 AND purpose = $2 AND id = $3
`

type SetSelectedUserChatModelParams struct {
	UserID    string
	Purpose   string
	ID        string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SetSelectedUserChatModel(ctx context.Context, arg SetSelectedUserChatModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSelectedUserChatModel,
		arg.UserID,
		arg.Purpose,
		arg.ID,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unsetSelectedUserChatModel = `-- name: UnsetSelectedUserChatModel :execrows
UPDATE user_chat_models
SET is_selected = FALSE,
    updated_at = $3
WHERE user_id = $1 AND purpose = $2 AND is_selected = TRUE
`

type UnsetSelectedUserChatModelParams struct {
	UserID    string
	Purpose   string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UnsetSelectedUserChatModel(ctx context.Context, arg UnsetSelectedUserChatModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, unsetSelectedUserChatModel, arg.UserID, arg.Purpose, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChatSession = `-- name: UpdateChatSession :execrows
UPDATE chat_sessions
SET user_id = $2,
    title = $3,
    pinned = $4,
    last_message_at = $5,
    created_at = $6,
    updated_at = $7
WHERE id = $1
`

type UpdateChatSessionParams struct {
	ID            string
	UserID        string
	Title         string
	Pinned        bool
	LastMessageAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateChatSession(ctx context.Context, arg UpdateChatSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChatSession,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Pinned,
		arg.LastMessageAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserChatModel = `-- name: UpdateUserChatModel :execrows
UPDATE user_chat_models
SET name = $3,
    base_url = $4,
    api_key_encrypted = $5,
    model_name = $6,
    temperature = $7,
    updated_at = $8
WHERE id = $1 AND user_id = $2
`

type UpdateUserChatModelParams struct {
	ID              string
	UserID          string
	Name            string
	BaseUrl         string
	ApiKeyEncrypted string
	ModelName       string
	Temperature     float64
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateUserChatModel(ctx context.Context, arg UpdateUserChatModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserChatModel,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.ModelName,
		arg.Temperature,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
