// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConnection = `-- name: CreateConnection :execrows
INSERT INTO knowledge_connections (
	id, user_id, provider, name, sync_enabled, last_synced_at, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateConnectionParams struct {
	ID           string
	UserID       string
	Provider     string
	Name         string
	SyncEnabled  bool
	LastSyncedAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateConnection(ctx context.Context, arg CreateConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createConnection,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Name,
		arg.SyncEnabled,
		arg.LastSyncedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSyncJob = `-- name: CreateSyncJob :execrows
INSERT INTO knowledge_sync_jobs (id, user_id, connection_id, status, summary, created_at, started_at, finished_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSyncJobParams struct {
	ID           string
	UserID       string
	ConnectionID string
	Status       string
	Summary      string
	CreatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
}

func (q *Queries) CreateSyncJob(ctx context.Context, arg CreateSyncJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSyncJob,
		arg.ID,
		arg.UserID,
		arg.ConnectionID,
		arg.Status,
		arg.Summary,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteConnection = `-- name: DeleteConnection :execrows
DELETE FROM knowledge_connections
WHERE id = $1 AND user_id = $2
`

type DeleteConnectionParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCorpusDocuments = `-- name: DeleteCorpusDocuments :execrows
DELETE FROM knowledge_documents
WHERE connection_id = $1
`

func (q *Queries) DeleteCorpusDocuments(ctx context.Context, connectionID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCorpusDocuments, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFeishuConnectionConfig = `-- name: DeleteFeishuConnectionConfig :execrows
DELETE FROM knowledge_connection_feishu_configs
WHERE connection_id = $1
`

func (q *Queries) DeleteFeishuConnectionConfig(ctx context.Context, connectionID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeishuConnectionConfig, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMetadata = `-- name: DeleteMetadata :execrows
DELETE FROM knowledge_document_meta
WHERE connection_id = $1
`

func (q *Queries) DeleteMetadata(ctx context.Context, connectionID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMetadata, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSourceDocuments = `-- name: DeleteSourceDocuments :execrows
DELETE FROM knowledge_source_documents
WHERE connection_id = $1
`

func (q *Queries) DeleteSourceDocuments(ctx context.Context, connectionID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSourceDocuments, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteYuqueConnectionConfig = `-- name: DeleteYuqueConnectionConfig :execrows
DELETE FROM knowledge_connection_yuque_configs
WHERE connection_id = $1
`

func (q *Queries) DeleteYuqueConnectionConfig(ctx context.Context, connectionID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteYuqueConnectionConfig, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnection = `-- name: GetConnection :one
SELECT id, user_id, provider, name, sync_enabled, last_synced_at, created_at, updated_at
FROM knowledge_connections
WHERE id = $1 AND user_id = $2
`

type GetConnectionParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (KnowledgeConnection, error) {
	row := q.db.QueryRow(ctx, getConnection, arg.ID, arg.UserID)
	var i KnowledgeConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Name,
		&i.SyncEnabled,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectionById = `-- name: GetConnectionById :one
SELECT id, user_id, provider, name, sync_enabled, last_synced_at, created_at, updated_at
FROM knowledge_connections
WHERE id = $1
`

func (q *Queries) GetConnectionById(ctx context.Context, id string) (KnowledgeConnection, error) {
	row := q.db.QueryRow(ctx, getConnectionById, id)
	var i KnowledgeConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Name,
		&i.SyncEnabled,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeishuConnectionConfig = `-- name: GetFeishuConnectionConfig :one
SELECT app_id, app_secret_encrypted, entry_type, entry_token, created_at, updated_at
FROM knowledge_connection_feishu_configs
WHERE connection_id = $1
`

type GetFeishuConnectionConfigRow struct {
	AppID              string
	AppSecretEncrypted string
	EntryType          string
	EntryToken         string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) GetFeishuConnectionConfig(ctx context.Context, connectionID string) (GetFeishuConnectionConfigRow, error) {
	row := q.db.QueryRow(ctx, getFeishuConnectionConfig, connectionID)
	var i GetFeishuConnectionConfigRow
	err := row.Scan(
		&i.AppID,
		&i.AppSecretEncrypted,
		&i.EntryType,
		&i.EntryToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSyncJob = `-- name: GetSyncJob :one
SELECT id, user_id, connection_id, status, summary, created_at, started_at, finished_at
FROM knowledge_sync_jobs
WHERE id = $1
`

func (q *Queries) GetSyncJob(ctx context.Context, id string) (KnowledgeSyncJob, error) {
	row := q.db.QueryRow(ctx, getSyncJob, id)
	var i KnowledgeSyncJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionID,
		&i.Status,
		&i.Summary,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getYuqueConnectionConfig = `-- name: GetYuqueConnectionConfig :one
SELECT token_encrypted, group_login, namespace, pending_docs_json, created_at, updated_at
FROM knowledge_connection_yuque_configs
WHERE connection_id = $1
`

type GetYuqueConnectionConfigRow struct {
	TokenEncrypted  string
	GroupLogin      string
	Namespace       pgtype.Text
	PendingDocsJson string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetYuqueConnectionConfig(ctx context.Context, connectionID string) (GetYuqueConnectionConfigRow, error) {
	row := q.db.QueryRow(ctx, getYuqueConnectionConfig, connectionID)
	var i GetYuqueConnectionConfigRow
	err := row.Scan(
		&i.TokenEncrypted,
		&i.GroupLogin,
		&i.Namespace,
		&i.PendingDocsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCorpusChunk = `-- name: InsertCorpusChunk :execrows
INSERT INTO knowledge_chunks (
	id, user_id, connection_id, document_id, chunk_index, content, content_hash, tsv, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, to_tsvector('simple', $6), $8)
`

type InsertCorpusChunkParams struct {
	ID           string
	UserID       string
	ConnectionID string
	DocumentID   string
	ChunkIndex   int32
	Content      string
	ContentHash  string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertCorpusChunk(ctx context.Context, arg InsertCorpusChunkParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCorpusChunk,
		arg.ID,
		arg.UserID,
		arg.ConnectionID,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.Content,
		arg.ContentHash,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCorpusDocument = `-- name: InsertCorpusDocument :execrows
INSERT INTO knowledge_documents (
	id, user_id, connection_id, repo, title, doc_ref, source_url, body_hash, updated_at, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertCorpusDocumentParams struct {
	ID           string
	UserID       string
	ConnectionID string
	Repo         string
	Title        string
	DocRef       string
	SourceUrl    pgtype.Text
	BodyHash     string
	UpdatedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertCorpusDocument(ctx context.Context, arg InsertCorpusDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCorpusDocument,
		arg.ID,
		arg.UserID,
		arg.ConnectionID,
		arg.Repo,
		arg.Title,
		arg.DocRef,
		arg.SourceUrl,
		arg.BodyHash,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertMetadata = `-- name: InsertMetadata :execrows
INSERT INTO knowledge_document_meta (
	id, user_id, connection_id, repo, title, doc_ref, source_url, chunk_count, updated_at, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertMetadataParams struct {
	ID           string
	UserID       string
	ConnectionID string
	Repo         string
	Title        string
	DocRef       string
	SourceUrl    pgtype.Text
	ChunkCount   int32
	UpdatedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertMetadata(ctx context.Context, arg InsertMetadataParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMetadata,
		arg.ID,
		arg.UserID,
		arg.ConnectionID,
		arg.Repo,
		arg.Title,
		arg.DocRef,
		arg.SourceUrl,
		arg.ChunkCount,
		arg.UpdatedAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSourceDocument = `-- name: InsertSourceDocument :execrows
INSERT INTO knowledge_source_documents (
	id, user_id, connection_id, provider, external_id, repo, title, doc_ref, source_url, raw_body, body_hash, source_updated_at, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertSourceDocumentParams struct {
	ID              string
	UserID          string
	ConnectionID    string
	Provider        string
	ExternalID      string
	Repo            string
	Title           string
	DocRef          string
	SourceUrl       pgtype.Text
	RawBody         string
	BodyHash        string
	SourceUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertSourceDocument(ctx context.Context, arg InsertSourceDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSourceDocument,
		arg.ID,
		arg.UserID,
		arg.ConnectionID,
		arg.Provider,
		arg.ExternalID,
		arg.Repo,
		arg.Title,
		arg.DocRef,
		arg.SourceUrl,
		arg.RawBody,
		arg.BodyHash,
		arg.SourceUpdatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listConnections = `-- name: ListConnections :many
SELECT id, user_id, provider, name, sync_enabled, last_synced_at, created_at, updated_at
FROM knowledge_connections
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListConnections(ctx context.Context, userID string) ([]KnowledgeConnection, error) {
	rows, err := q.db.Query(ctx, listConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeConnection
	for rows.Next() {
		var i KnowledgeConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Name,
			&i.SyncEnabled,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorpusChunks = `-- name: ListCorpusChunks :many
SELECT id, user_id, connection_id, document_id, chunk_index, content, content_hash, created_at
FROM knowledge_chunks
WHERE connection_id = $1
ORDER BY created_at ASC, document_id ASC, chunk_index ASC
`

type ListCorpusChunksRow struct {
	ID           string
	UserID       string
	ConnectionID string
	DocumentID   string
	ChunkIndex   int32
	Content      string
	ContentHash  string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListCorpusChunks(ctx context.Context, connectionID string) ([]ListCorpusChunksRow, error) {
	rows, err := q.db.Query(ctx, listCorpusChunks, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCorpusChunksRow
	for rows.Next() {
		var i ListCorpusChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.Content,
			&i.ContentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorpusDocuments = `-- name: ListCorpusDocuments :many
SELECT id, user_id, connection_id, repo, title, doc_ref, source_url, body_hash, updated_at, created_at
FROM knowledge_documents
WHERE connection_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListCorpusDocuments(ctx context.Context, connectionID string) ([]KnowledgeDocument, error) {
	rows, err := q.db.Query(ctx, listCorpusDocuments, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeDocument
	for rows.Next() {
		var i KnowledgeDocument
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.Repo,
			&i.Title,
			&i.DocRef,
			&i.SourceUrl,
			&i.BodyHash,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetadata = `-- name: ListMetadata :many
SELECT id, user_id, connection_id, repo, title, doc_ref, source_url, chunk_count, updated_at, created_at
FROM knowledge_document_meta
WHERE connection_id = $1
ORDER BY repo ASC, updated_at DESC, title ASC
`

func (q *Queries) ListMetadata(ctx context.Context, connectionID string) ([]KnowledgeDocumentMetum, error) {
	rows, err := q.db.Query(ctx, listMetadata, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeDocumentMetum
	for rows.Next() {
		var i KnowledgeDocumentMetum
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.Repo,
			&i.Title,
			&i.DocRef,
			&i.SourceUrl,
			&i.ChunkCount,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceDocuments = `-- name: ListSourceDocuments :many
SELECT id, user_id, connection_id, provider, external_id, repo, title, doc_ref, source_url, raw_body, body_hash, source_updated_at, created_at, updated_at
FROM knowledge_source_documents
WHERE connection_id = $1
ORDER BY source_updated_at DESC, title ASC
`

func (q *Queries) ListSourceDocuments(ctx context.Context, connectionID string) ([]KnowledgeSourceDocument, error) {
	rows, err := q.db.Query(ctx, listSourceDocuments, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeSourceDocument
	for rows.Next() {
		var i KnowledgeSourceDocument
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.Provider,
			&i.ExternalID,
			&i.Repo,
			&i.Title,
			&i.DocRef,
			&i.SourceUrl,
			&i.RawBody,
			&i.BodyHash,
			&i.SourceUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncJobs = `-- name: ListSyncJobs :many
SELECT id, user_id, connection_id, status, summary, created_at, started_at, finished_at
FROM knowledge_sync_jobs
WHERE user_id = $1 AND connection_id = $2
ORDER BY created_at DESC
`

type ListSyncJobsParams struct {
	UserID       string
	ConnectionID string
}

func (q *Queries) ListSyncJobs(ctx context.Context, arg ListSyncJobsParams) ([]KnowledgeSyncJob, error) {
	rows, err := q.db.Query(ctx, listSyncJobs, arg.UserID, arg.ConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeSyncJob
	for rows.Next() {
		var i KnowledgeSyncJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionID,
			&i.Status,
			&i.Summary,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKnowledgeAllConnections = `-- name: SearchKnowledgeAllConnections :many
SELECT kd.connection_id, kd.id, kch.id, kc.provider, kd.title, kd.repo, COALESCE(kd.source_url, ''), kch.content
FROM knowledge_chunks kch
INNER JOIN knowledge_documents kd ON kd.id = kch.document_id
INNER JOIN knowledge_connections kc ON kc.id = kd.connection_id
WHERE kc.user_id = $1
ORDER BY kd.updated_at DESC, kch.chunk_index ASC
LIMIT 4000
`

type SearchKnowledgeAllConnectionsRow struct {
	ConnectionID string
	ID           string
	ID_2         string
	Provider     string
	Title        string
	Repo         string
	SourceUrl    string
	Content      string
}

func (q *Queries) SearchKnowledgeAllConnections(ctx context.Context, userID string) ([]SearchKnowledgeAllConnectionsRow, error) {
	rows, err := q.db.Query(ctx, searchKnowledgeAllConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchKnowledgeAllConnectionsRow
	for rows.Next() {
		var i SearchKnowledgeAllConnectionsRow
		if err := rows.Scan(
			&i.ConnectionID,
			&i.ID,
			&i.ID_2,
			&i.Provider,
			&i.Title,
			&i.Repo,
			&i.SourceUrl,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKnowledgeSelectedConnections = `-- name: SearchKnowledgeSelectedConnections :many
SELECT kd.connection_id, kd.id, kch.id, kc.provider, kd.title, kd.repo, COALESCE(kd.source_url, ''), kch.content
FROM knowledge_chunks kch
INNER JOIN knowledge_documents kd ON kd.id = kch.document_id
INNER JOIN knowledge_connections kc ON kc.id = kd.connection_id
WHERE kc.user_id = $1
  AND kd.connection_id = ANY($2::text[])
ORDER BY kd.updated_at DESC, kch.chunk_index ASC
LIMIT 4000
`

type SearchKnowledgeSelectedConnectionsParams struct {
	UserID  string
	Column2 []string
}

type SearchKnowledgeSelectedConnectionsRow struct {
	ConnectionID string
	ID           string
	ID_2         string
	Provider     string
	Title        string
	Repo         string
	SourceUrl    string
	Content      string
}

func (q *Queries) SearchKnowledgeSelectedConnections(ctx context.Context, arg SearchKnowledgeSelectedConnectionsParams) ([]SearchKnowledgeSelectedConnectionsRow, error) {
	rows, err := q.db.Query(ctx, searchKnowledgeSelectedConnections, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchKnowledgeSelectedConnectionsRow
	for rows.Next() {
		var i SearchKnowledgeSelectedConnectionsRow
		if err := rows.Scan(
			&i.ConnectionID,
			&i.ID,
			&i.ID_2,
			&i.Provider,
			&i.Title,
			&i.Repo,
			&i.SourceUrl,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnection = `-- name: UpdateConnection :execrows
UPDATE knowledge_connections
SET user_id = $2,
    provider = $3,
    name = $4,
    sync_enabled = $5,
    last_synced_at = $6,
    created_at = $7,
    updated_at = $8
WHERE id = $1
`

type UpdateConnectionParams struct {
	ID           string
	UserID       string
	Provider     string
	Name         string
	SyncEnabled  bool
	LastSyncedAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateConnection,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Name,
		arg.SyncEnabled,
		arg.LastSyncedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSyncJob = `-- name: UpdateSyncJob :execrows
UPDATE knowledge_sync_jobs
SET user_id = $2,
    connection_id = $3,
    status = $4,
    summary = $5,
    created_at = $6,
    started_at = $7,
    finished_at = $8
WHERE id = $1
`

type UpdateSyncJobParams struct {
	ID           string
	UserID       string
	ConnectionID string
	Status       string
	Summary      string
	CreatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateSyncJob(ctx context.Context, arg UpdateSyncJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSyncJob,
		arg.ID,
		arg.UserID,
		arg.ConnectionID,
		arg.Status,
		arg.Summary,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertFeishuConnectionConfig = `-- name: UpsertFeishuConnectionConfig :execrows
INSERT INTO knowledge_connection_feishu_configs (
	connection_id, app_id, app_secret_encrypted, entry_type, entry_token, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (connection_id) DO UPDATE
SET app_id = EXCLUDED.app_id,
    app_secret_encrypted = EXCLUDED.app_secret_encrypted,
    entry_type = EXCLUDED.entry_type,
    entry_token = EXCLUDED.entry_token,
    updated_at = EXCLUDED.updated_at
`

type UpsertFeishuConnectionConfigParams struct {
	ConnectionID       string
	AppID              string
	AppSecretEncrypted string
	EntryType          string
	EntryToken         string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpsertFeishuConnectionConfig(ctx context.Context, arg UpsertFeishuConnectionConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertFeishuConnectionConfig,
		arg.ConnectionID,
		arg.AppID,
		arg.AppSecretEncrypted,
		arg.EntryType,
		arg.EntryToken,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertYuqueConnectionConfig = `-- name: UpsertYuqueConnectionConfig :execrows
INSERT INTO knowledge_connection_yuque_configs (
	connection_id, token_encrypted, group_login, namespace, pending_docs_json, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (connection_id) DO UPDATE
SET token_encrypted = EXCLUDED.token_encrypted,
    group_login = EXCLUDED.group_login,
    namespace = EXCLUDED.namespace,
    pending_docs_json = EXCLUDED.pending_docs_json,
    updated_at = EXCLUDED.updated_at
`

type UpsertYuqueConnectionConfigParams struct {
	ConnectionID    string
	TokenEncrypted  string
	GroupLogin      string
	Namespace       pgtype.Text
	PendingDocsJson string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertYuqueConnectionConfig(ctx context.Context, arg UpsertYuqueConnectionConfigParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertYuqueConnectionConfig,
		arg.ConnectionID,
		arg.TokenEncrypted,
		arg.GroupLogin,
		arg.Namespace,
		arg.PendingDocsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
