// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mirror.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMirrorTask = `-- name: CreateMirrorTask :execrows
INSERT INTO mirror_tasks (
	id, kind, user_id, resource_id, status, payload, attempts, last_error,
	next_retry_at, created_at, updated_at, completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateMirrorTaskParams struct {
	ID          string
	Kind        string
	UserID      string
	ResourceID  string
	Status      string
	Payload     string
	Attempts    int32
	LastError   string
	NextRetryAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) CreateMirrorTask(ctx context.Context, arg CreateMirrorTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, createMirrorTask,
		arg.ID,
		arg.Kind,
		arg.UserID,
		arg.ResourceID,
		arg.Status,
		arg.Payload,
		arg.Attempts,
		arg.LastError,
		arg.NextRetryAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMirrorTask = `-- name: GetMirrorTask :one
SELECT id, kind, user_id, resource_id, status, payload, attempts, last_error,
       next_retry_at, created_at, updated_at, completed_at
FROM mirror_tasks
WHERE id = $1
`

func (q *Queries) GetMirrorTask(ctx context.Context, id string) (MirrorTask, error) {
	row := q.db.QueryRow(ctx, getMirrorTask, id)
	var i MirrorTask
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.UserID,
		&i.ResourceID,
		&i.Status,
		&i.Payload,
		&i.Attempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listDueMirrorTasks = `-- name: ListDueMirrorTasks :many
SELECT id, kind, user_id, resource_id, status, payload, attempts, last_error,
       next_retry_at, created_at, updated_at, completed_at
FROM mirror_tasks
WHERE status = $1 AND next_retry_at <= $2
ORDER BY next_retry_at ASC, created_at ASC
LIMIT $3
`

type ListDueMirrorTasksParams struct {
	Status      string
	NextRetryAt pgtype.Timestamptz
	Limit       int32
}

func (q *Queries) ListDueMirrorTasks(ctx context.Context, arg ListDueMirrorTasksParams) ([]MirrorTask, error) {
	rows, err := q.db.Query(ctx, listDueMirrorTasks, arg.Status, arg.NextRetryAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MirrorTask
	for rows.Next() {
		var i MirrorTask
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.UserID,
			&i.ResourceID,
			&i.Status,
			&i.Payload,
			&i.Attempts,
			&i.LastError,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMirrorTask = `-- name: UpdateMirrorTask :execrows
UPDATE mirror_tasks
SET kind = $2,
    user_id = $3,
    resource_id = $4,
    status = $5,
    payload = $6,
    attempts = $7,
    last_error = $8,
    next_retry_at = $9,
    created_at = $10,
    updated_at = $11,
    completed_at = $12
WHERE id = $1
`

type UpdateMirrorTaskParams struct {
	ID          string
	Kind        string
	UserID      string
	ResourceID  string
	Status      string
	Payload     string
	Attempts    int32
	LastError   string
	NextRetryAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) UpdateMirrorTask(ctx context.Context, arg UpdateMirrorTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMirrorTask,
		arg.ID,
		arg.Kind,
		arg.UserID,
		arg.ResourceID,
		arg.Status,
		arg.Payload,
		arg.Attempts,
		arg.LastError,
		arg.NextRetryAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
