// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AuthIdentity struct {
	ID              string
	UserID          string
	Provider        string
	ProviderSubject string
	Email           string
	EmailVerified   bool
	AvatarUrl       string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ChatMessage struct {
	ID               string
	SessionID        string
	UserID           string
	Role             string
	Content          string
	Skill            string
	UseKnowledge     bool
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	CreatedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}

type ChatMessageSource struct {
	ID               string
	MessageID        string
	Provider         string
	ConnectionID     string
	DocumentID       string
	ChunkID          string
	Title            string
	Repo             string
	Url              string
	Snippet          string
	Score            float64
	CreatedAt        pgtype.Timestamptz
	MatchedLinesJson string
}

type ChatSession struct {
	ID            string
	UserID        string
	Title         string
	Pinned        bool
	LastMessageAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type KnowledgeChunk struct {
	ID           string
	UserID       string
	ConnectionID string
	DocumentID   string
	ChunkIndex   int32
	Content      string
	ContentHash  string
	Embedding    pgvector.Vector
	Tsv          interface{}
	CreatedAt    pgtype.Timestamptz
}

type KnowledgeConnection struct {
	ID           string
	UserID       string
	Provider     string
	Name         string
	SyncEnabled  bool
	LastSyncedAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type KnowledgeConnectionFeishuConfig struct {
	ConnectionID       string
	AppID              string
	AppSecretEncrypted string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	EntryType          string
	EntryToken         string
}

type KnowledgeConnectionYuqueConfig struct {
	ConnectionID    string
	TokenEncrypted  string
	GroupLogin      string
	Namespace       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	PendingDocsJson string
}

type KnowledgeDocument struct {
	ID           string
	UserID       string
	ConnectionID string
	Repo         string
	Title        string
	DocRef       string
	SourceUrl    pgtype.Text
	BodyHash     string
	UpdatedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type KnowledgeDocumentMetum struct {
	ID           string
	UserID       string
	ConnectionID string
	Repo         string
	Title        string
	DocRef       string
	SourceUrl    pgtype.Text
	ChunkCount   int32
	UpdatedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type KnowledgeSourceDocument struct {
	ID              string
	UserID          string
	ConnectionID    string
	Provider        string
	ExternalID      string
	Repo            string
	Title           string
	DocRef          string
	SourceUrl       pgtype.Text
	RawBody         string
	BodyHash        string
	SourceUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type KnowledgeSyncJob struct {
	ID           string
	UserID       string
	ConnectionID string
	Status       string
	Summary      string
	CreatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
}

type MirrorTask struct {
	ID          string
	Kind        string
	UserID      string
	ResourceID  string
	Status      string
	Payload     string
	Attempts    int32
	LastError   string
	NextRetryAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

type Run struct {
	ID                     string
	UserID                 string
	Title                  string
	Goal                   string
	RequestedMode          string
	KnowledgeConnectionIds []string
	EffectiveMode          string
	Status                 string
	LatestArtifactID       string
	ErrorMessage           string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	SkillInstallationID    string
	SkillSnapshotID        string
}

type RunArtifact struct {
	ID              string
	RunID           string
	Kind            string
	ContentMarkdown string
	Version         int32
	CreatedAt       pgtype.Timestamptz
}

type RunSource struct {
	ID           string
	RunID        string
	Provider     string
	ConnectionID string
	DocumentID   string
	ChunkID      string
	Title        string
	Repo         string
	Url          string
	Snippet      string
	Score        float64
	CreatedAt    pgtype.Timestamptz
}

type RunStep struct {
	ID         string
	RunID      string
	Kind       string
	Label      string
	Status     string
	Summary    string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Session struct {
	ID           string
	UserID       string
	AccessToken  string
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type Skill struct {
	ID          string
	UserID      string
	Slug        string
	Title       string
	Description string
	Prompt      string
	Mode        string
	Source      string
	Enabled     bool
	RepoUrl     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SkillArtifact struct {
	ID               string
	UserID           string
	DefinitionID     string
	RevisionID       string
	Source           string
	FileName         string
	MediaType        string
	SourceUrl        string
	Sha256           string
	SizeBytes        int64
	EntryPath        string
	ManifestPath     string
	InstructionsPath string
	ArchiveBytes     []byte
	CreatedAt        pgtype.Timestamptz
}

type SkillArtifactFile struct {
	ID             string
	ArtifactID     string
	UserID         string
	Path           string
	MediaType      string
	SizeBytes      int64
	Sha256         string
	IsManifest     bool
	IsInstructions bool
	CreatedAt      pgtype.Timestamptz
}

type SkillDefinition struct {
	ID        string
	UserID    string
	Slug      string
	Kind      string
	Source    string
	RepoUrl   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SkillImportJob struct {
	ID             string
	UserID         string
	Source         string
	Status         string
	ArtifactID     string
	DefinitionID   string
	RevisionID     string
	InstallationID string
	ErrorMessage   string
	RequestJson    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type SkillInstallation struct {
	ID                string
	UserID            string
	DefinitionID      string
	CurrentRevisionID string
	Enabled           bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Name              string
	IsDefault         bool
}

type SkillRevision struct {
	ID           string
	DefinitionID string
	Version      int32
	Title        string
	Description  string
	Prompt       string
	Mode         string
	ManifestJson string
	CreatedAt    pgtype.Timestamptz
}

type SkillRuntimeSnapshot struct {
	ID              string
	Scope           string
	ScopeID         string
	UserID          string
	InstallationID  string
	DefinitionID    string
	RevisionID      string
	Kind            string
	Title           string
	Description     string
	Mode            string
	Prompt          string
	RuntimeSpecJson string
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID           string
	Username     string
	DisplayName  string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	Email        string
	AvatarUrl    string
}

type UserChatModel struct {
	ID              string
	UserID          string
	Purpose         string
	ModelName       string
	IsSelected      bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Name            string
	BaseUrl         string
	ApiKeyEncrypted string
	Origin          string
	Temperature     float64
}
