// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRun = `-- name: CreateRun :execrows
INSERT INTO runs (
	id, user_id, title, goal, requested_mode, knowledge_connection_ids,
	skill_installation_id, skill_snapshot_id, effective_mode, status,
	latest_artifact_id, error_message, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateRunParams struct {
	ID                     string
	UserID                 string
	Title                  string
	Goal                   string
	RequestedMode          string
	KnowledgeConnectionIds []string
	SkillInstallationID    string
	SkillSnapshotID        string
	EffectiveMode          string
	Status                 string
	LatestArtifactID       string
	ErrorMessage           string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, createRun,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Goal,
		arg.RequestedMode,
		arg.KnowledgeConnectionIds,
		arg.SkillInstallationID,
		arg.SkillSnapshotID,
		arg.EffectiveMode,
		arg.Status,
		arg.LatestArtifactID,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRunSources = `-- name: DeleteRunSources :execrows
DELETE FROM run_sources
WHERE run_id = $1
`

func (q *Queries) DeleteRunSources(ctx context.Context, runID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRunSources, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRun = `-- name: GetRun :one
SELECT id, user_id, title, goal, requested_mode, knowledge_connection_ids,
       skill_installation_id, skill_snapshot_id, effective_mode, status,
       latest_artifact_id, error_message, created_at, updated_at
FROM runs
WHERE id = $1 AND user_id = $2
`

type GetRunParams struct {
	ID     string
	UserID string
}

type GetRunRow struct {
	ID                     string
	UserID                 string
	Title                  string
	Goal                   string
	RequestedMode          string
	KnowledgeConnectionIds []string
	SkillInstallationID    string
	SkillSnapshotID        string
	EffectiveMode          string
	Status                 string
	LatestArtifactID       string
	ErrorMessage           string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (GetRunRow, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.UserID)
	var i GetRunRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Goal,
		&i.RequestedMode,
		&i.KnowledgeConnectionIds,
		&i.SkillInstallationID,
		&i.SkillSnapshotID,
		&i.EffectiveMode,
		&i.Status,
		&i.LatestArtifactID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunById = `-- name: GetRunById :one
SELECT id, user_id, title, goal, requested_mode, knowledge_connection_ids,
       skill_installation_id, skill_snapshot_id, effective_mode, status,
       latest_artifact_id, error_message, created_at, updated_at
FROM runs
WHERE id = $1
`

type GetRunByIdRow struct {
	ID                     string
	UserID                 string
	Title                  string
	Goal                   string
	RequestedMode          string
	KnowledgeConnectionIds []string
	SkillInstallationID    string
	SkillSnapshotID        string
	EffectiveMode          string
	Status                 string
	LatestArtifactID       string
	ErrorMessage           string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) GetRunById(ctx context.Context, id string) (GetRunByIdRow, error) {
	row := q.db.QueryRow(ctx, getRunById, id)
	var i GetRunByIdRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Goal,
		&i.RequestedMode,
		&i.KnowledgeConnectionIds,
		&i.SkillInstallationID,
		&i.SkillSnapshotID,
		&i.EffectiveMode,
		&i.Status,
		&i.LatestArtifactID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRunSource = `-- name: InsertRunSource :execrows
INSERT INTO run_sources (id, run_id, provider, connection_id, document_id, chunk_id, title, repo, url, snippet, score, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertRunSourceParams struct {
	ID           string
	RunID        string
	Provider     string
	ConnectionID string
	DocumentID   string
	ChunkID      string
	Title        string
	Repo         string
	Url          string
	Snippet      string
	Score        float64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertRunSource(ctx context.Context, arg InsertRunSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRunSource,
		arg.ID,
		arg.RunID,
		arg.Provider,
		arg.ConnectionID,
		arg.DocumentID,
		arg.ChunkID,
		arg.Title,
		arg.Repo,
		arg.Url,
		arg.Snippet,
		arg.Score,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, run_id, kind, content_markdown, version, created_at
FROM run_artifacts
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListArtifacts(ctx context.Context, runID string) ([]RunArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifacts, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunArtifact
	for rows.Next() {
		var i RunArtifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.ContentMarkdown,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSources = `-- name: ListRunSources :many
SELECT id, run_id, provider, connection_id, document_id, chunk_id, title, repo, url, snippet, score, created_at
FROM run_sources
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRunSources(ctx context.Context, runID string) ([]RunSource, error) {
	rows, err := q.db.Query(ctx, listRunSources, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunSource
	for rows.Next() {
		var i RunSource
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Provider,
			&i.ConnectionID,
			&i.DocumentID,
			&i.ChunkID,
			&i.Title,
			&i.Repo,
			&i.Url,
			&i.Snippet,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunSteps = `-- name: ListRunSteps :many
SELECT id, run_id, kind, label, status, summary, started_at, finished_at, created_at
FROM run_steps
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRunSteps(ctx context.Context, runID string) ([]RunStep, error) {
	rows, err := q.db.Query(ctx, listRunSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunStep
	for rows.Next() {
		var i RunStep
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Kind,
			&i.Label,
			&i.Status,
			&i.Summary,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, user_id, title, goal, requested_mode, knowledge_connection_ids,
       skill_installation_id, skill_snapshot_id, effective_mode, status,
       latest_artifact_id, error_message, created_at, updated_at
FROM runs
WHERE user_id = $1
ORDER BY updated_at DESC
`

type ListRunsRow struct {
	ID                     string
	UserID                 string
	Title                  string
	Goal                   string
	RequestedMode          string
	KnowledgeConnectionIds []string
	SkillInstallationID    string
	SkillSnapshotID        string
	EffectiveMode          string
	Status                 string
	LatestArtifactID       string
	ErrorMessage           string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) ListRuns(ctx context.Context, userID string) ([]ListRunsRow, error) {
	rows, err := q.db.Query(ctx, listRuns, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunsRow
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Goal,
			&i.RequestedMode,
			&i.KnowledgeConnectionIds,
			&i.SkillInstallationID,
			&i.SkillSnapshotID,
			&i.EffectiveMode,
			&i.Status,
			&i.LatestArtifactID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveArtifact = `-- name: SaveArtifact :execrows
INSERT INTO run_artifacts (id, run_id, kind, content_markdown, version, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveArtifactParams struct {
	ID              string
	RunID           string
	Kind            string
	ContentMarkdown string
	Version         int32
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) SaveArtifact(ctx context.Context, arg SaveArtifactParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveArtifact,
		arg.ID,
		arg.RunID,
		arg.Kind,
		arg.ContentMarkdown,
		arg.Version,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRun = `-- name: UpdateRun :execrows
UPDATE runs
SET user_id = $2,
    title = $3,
    goal = $4,
    requested_mode = $5,
    knowledge_connection_ids = $6,
    skill_installation_id = $7,
    skill_snapshot_id = $8,
    effective_mode = $9,
    status = $10,
    latest_artifact_id = $11,
    error_message = $12,
    created_at = $13,
    updated_at = $14
WHERE id = $1
`

type UpdateRunParams struct {
	ID                     string
	UserID                 string
	Title                  string
	Goal                   string
	RequestedMode          string
	KnowledgeConnectionIds []string
	SkillInstallationID    string
	SkillSnapshotID        string
	EffectiveMode          string
	Status                 string
	LatestArtifactID       string
	ErrorMessage           string
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRun,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Goal,
		arg.RequestedMode,
		arg.KnowledgeConnectionIds,
		arg.SkillInstallationID,
		arg.SkillSnapshotID,
		arg.EffectiveMode,
		arg.Status,
		arg.LatestArtifactID,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRunStep = `-- name: UpsertRunStep :execrows
INSERT INTO run_steps (id, run_id, kind, label, status, summary, started_at, finished_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
	kind = EXCLUDED.kind,
	label = EXCLUDED.label,
	status = EXCLUDED.status,
	summary = EXCLUDED.summary,
	started_at = EXCLUDED.started_at,
	finished_at = EXCLUDED.finished_at,
	created_at = EXCLUDED.created_at
`

type UpsertRunStepParams struct {
	ID         string
	RunID      string
	Kind       string
	Label      string
	Status     string
	Summary    string
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) UpsertRunStep(ctx context.Context, arg UpsertRunStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertRunStep,
		arg.ID,
		arg.RunID,
		arg.Kind,
		arg.Label,
		arg.Status,
		arg.Summary,
		arg.StartedAt,
		arg.FinishedAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
