// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefinitionDefaultInstallations = `-- name: ClearDefinitionDefaultInstallations :execrows
UPDATE skill_installations
SET is_default = FALSE
WHERE user_id = $1 AND definition_id = $2 AND is_default = TRUE
`

type ClearDefinitionDefaultInstallationsParams struct {
	UserID       string
	DefinitionID string
}

func (q *Queries) ClearDefinitionDefaultInstallations(ctx context.Context, arg ClearDefinitionDefaultInstallationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearDefinitionDefaultInstallations, arg.UserID, arg.DefinitionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearOtherDefaultInstallations = `-- name: ClearOtherDefaultInstallations :execrows
UPDATE skill_installations
SET is_default = FALSE
WHERE user_id = $1 AND definition_id = $2 AND id <> $3 AND is_default = TRUE
`

type ClearOtherDefaultInstallationsParams struct {
	UserID       string
	DefinitionID string
	ID           string
}

func (q *Queries) ClearOtherDefaultInstallations(ctx context.Context, arg ClearOtherDefaultInstallationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearOtherDefaultInstallations, arg.UserID, arg.DefinitionID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countDefinitionInstallations = `-- name: CountDefinitionInstallations :one
SELECT COUNT(1)
FROM skill_installations
WHERE user_id = $1 AND definition_id = $2
`

type CountDefinitionInstallationsParams struct {
	UserID       string
	DefinitionID string
}

func (q *Queries) CountDefinitionInstallations(ctx context.Context, arg CountDefinitionInstallationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDefinitionInstallations, arg.UserID, arg.DefinitionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSkillArtifact = `-- name: CreateSkillArtifact :execrows
INSERT INTO skill_artifacts (
	id, user_id, definition_id, revision_id, source, file_name, media_type, source_url,
	sha256, size_bytes, entry_path, manifest_path, instructions_path, archive_bytes, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type CreateSkillArtifactParams struct {
	ID               string
	UserID           string
	DefinitionID     string
	RevisionID       string
	Source           string
	FileName         string
	MediaType        string
	SourceUrl        string
	Sha256           string
	SizeBytes        int64
	EntryPath        string
	ManifestPath     string
	InstructionsPath string
	ArchiveBytes     []byte
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateSkillArtifact(ctx context.Context, arg CreateSkillArtifactParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSkillArtifact,
		arg.ID,
		arg.UserID,
		arg.DefinitionID,
		arg.RevisionID,
		arg.Source,
		arg.FileName,
		arg.MediaType,
		arg.SourceUrl,
		arg.Sha256,
		arg.SizeBytes,
		arg.EntryPath,
		arg.ManifestPath,
		arg.InstructionsPath,
		arg.ArchiveBytes,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSkillDefinition = `-- name: CreateSkillDefinition :execrows
INSERT INTO skill_definitions (
	id, user_id, slug, kind, source, repo_url, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSkillDefinitionParams struct {
	ID        string
	UserID    string
	Slug      string
	Kind      string
	Source    string
	RepoUrl   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSkillDefinition(ctx context.Context, arg CreateSkillDefinitionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSkillDefinition,
		arg.ID,
		arg.UserID,
		arg.Slug,
		arg.Kind,
		arg.Source,
		arg.RepoUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSkillImportJob = `-- name: CreateSkillImportJob :execrows
INSERT INTO skill_import_jobs (
	id, user_id, source, status, artifact_id, definition_id, revision_id, installation_id,
	error_message, request_json, created_at, updated_at, completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateSkillImportJobParams struct {
	ID             string
	UserID         string
	Source         string
	Status         string
	ArtifactID     string
	DefinitionID   string
	RevisionID     string
	InstallationID string
	ErrorMessage   string
	RequestJson    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

func (q *Queries) CreateSkillImportJob(ctx context.Context, arg CreateSkillImportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSkillImportJob,
		arg.ID,
		arg.UserID,
		arg.Source,
		arg.Status,
		arg.ArtifactID,
		arg.DefinitionID,
		arg.RevisionID,
		arg.InstallationID,
		arg.ErrorMessage,
		arg.RequestJson,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSkillInstallation = `-- name: CreateSkillInstallation :execrows
INSERT INTO skill_installations (
	id, user_id, definition_id, current_revision_id, name, is_default, enabled, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateSkillInstallationParams struct {
	ID                string
	UserID            string
	DefinitionID      string
	CurrentRevisionID string
	Name              string
	IsDefault         bool
	Enabled           bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateSkillInstallation(ctx context.Context, arg CreateSkillInstallationParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSkillInstallation,
		arg.ID,
		arg.UserID,
		arg.DefinitionID,
		arg.CurrentRevisionID,
		arg.Name,
		arg.IsDefault,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSkillRevision = `-- name: CreateSkillRevision :execrows
INSERT INTO skill_revisions (
	id, definition_id, version, title, description, prompt, mode, manifest_json, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateSkillRevisionParams struct {
	ID           string
	DefinitionID string
	Version      int32
	Title        string
	Description  string
	Prompt       string
	Mode         string
	ManifestJson string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateSkillRevision(ctx context.Context, arg CreateSkillRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSkillRevision,
		arg.ID,
		arg.DefinitionID,
		arg.Version,
		arg.Title,
		arg.Description,
		arg.Prompt,
		arg.Mode,
		arg.ManifestJson,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSkillRuntimeSnapshot = `-- name: CreateSkillRuntimeSnapshot :execrows
INSERT INTO skill_runtime_snapshots (
	id, scope, scope_id, user_id, installation_id, definition_id, revision_id,
	kind, title, description, mode, prompt, runtime_spec_json, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type CreateSkillRuntimeSnapshotParams struct {
	ID              string
	Scope           string
	ScopeID         string
	UserID          string
	InstallationID  string
	DefinitionID    string
	RevisionID      string
	Kind            string
	Title           string
	Description     string
	Mode            string
	Prompt          string
	RuntimeSpecJson string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateSkillRuntimeSnapshot(ctx context.Context, arg CreateSkillRuntimeSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSkillRuntimeSnapshot,
		arg.ID,
		arg.Scope,
		arg.ScopeID,
		arg.UserID,
		arg.InstallationID,
		arg.DefinitionID,
		arg.RevisionID,
		arg.Kind,
		arg.Title,
		arg.Description,
		arg.Mode,
		arg.Prompt,
		arg.RuntimeSpecJson,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSkillArtifactFiles = `-- name: DeleteSkillArtifactFiles :execrows
DELETE FROM skill_artifact_files
WHERE artifact_id = $1
`

func (q *Queries) DeleteSkillArtifactFiles(ctx context.Context, artifactID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkillArtifactFiles, artifactID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSkillInstallation = `-- name: DeleteSkillInstallation :execrows
DELETE FROM skill_installations
WHERE id = $1 AND user_id = $2
`

type DeleteSkillInstallationParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteSkillInstallation(ctx context.Context, arg DeleteSkillInstallationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkillInstallation, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureSkillDefinitionExists = `-- name: EnsureSkillDefinitionExists :one
SELECT 1
FROM skill_definitions
WHERE id = $1 AND user_id = $2
`

type EnsureSkillDefinitionExistsParams struct {
	ID     string
	UserID string
}

func (q *Queries) EnsureSkillDefinitionExists(ctx context.Context, arg EnsureSkillDefinitionExistsParams) (int32, error) {
	row := q.db.QueryRow(ctx, ensureSkillDefinitionExists, arg.ID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getDefaultSkillInstallationRecord = `-- name: GetDefaultSkillInstallationRecord :one
SELECT si.id, si.user_id, si.definition_id, si.current_revision_id, si.name, si.is_default, si.enabled, si.created_at, si.updated_at,
       sd.id, sd.user_id, sd.slug, sd.kind, sd.source, sd.repo_url, sd.created_at, sd.updated_at,
       sr.id, sr.definition_id, sr.version, sr.title, sr.description, sr.prompt, sr.mode, sr.manifest_json, sr.created_at
FROM skill_installations si
JOIN skill_definitions sd ON sd.id = si.definition_id
JOIN skill_revisions sr ON sr.id = si.current_revision_id
WHERE si.user_id = $1 AND si.definition_id = $2
ORDER BY si.is_default DESC, si.updated_at DESC
LIMIT 1
`

type GetDefaultSkillInstallationRecordParams struct {
	UserID       string
	DefinitionID string
}

type GetDefaultSkillInstallationRecordRow struct {
	ID                string
	UserID            string
	DefinitionID      string
	CurrentRevisionID string
	Name              string
	IsDefault         bool
	Enabled           bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ID_2              string
	UserID_2          string
	Slug              string
	Kind              string
	Source            string
	RepoUrl           string
	CreatedAt_2       pgtype.Timestamptz
	UpdatedAt_2       pgtype.Timestamptz
	ID_3              string
	DefinitionID_2    string
	Version           int32
	Title             string
	Description       string
	Prompt            string
	Mode              string
	ManifestJson      string
	CreatedAt_3       pgtype.Timestamptz
}

func (q *Queries) GetDefaultSkillInstallationRecord(ctx context.Context, arg GetDefaultSkillInstallationRecordParams) (GetDefaultSkillInstallationRecordRow, error) {
	row := q.db.QueryRow(ctx, getDefaultSkillInstallationRecord, arg.UserID, arg.DefinitionID)
	var i GetDefaultSkillInstallationRecordRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DefinitionID,
		&i.CurrentRevisionID,
		&i.Name,
		&i.IsDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.UserID_2,
		&i.Slug,
		&i.Kind,
		&i.Source,
		&i.RepoUrl,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.ID_3,
		&i.DefinitionID_2,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.Prompt,
		&i.Mode,
		&i.ManifestJson,
		&i.CreatedAt_3,
	)
	return i, err
}

const getDeletedSkillContext = `-- name: GetDeletedSkillContext :one
SELECT definition_id, is_default
FROM skill_installations
WHERE id = $1 AND user_id = $2
`

type GetDeletedSkillContextParams struct {
	ID     string
	UserID string
}

type GetDeletedSkillContextRow struct {
	DefinitionID string
	IsDefault    bool
}

func (q *Queries) GetDeletedSkillContext(ctx context.Context, arg GetDeletedSkillContextParams) (GetDeletedSkillContextRow, error) {
	row := q.db.QueryRow(ctx, getDeletedSkillContext, arg.ID, arg.UserID)
	var i GetDeletedSkillContextRow
	err := row.Scan(&i.DefinitionID, &i.IsDefault)
	return i, err
}

const getInstallationRevisionTitle = `-- name: GetInstallationRevisionTitle :one
SELECT sr.title
FROM skill_definitions sd
JOIN skill_revisions sr ON sr.id = $2 AND sr.definition_id = sd.id
WHERE sd.id = $1 AND sd.user_id = $3
`

type GetInstallationRevisionTitleParams struct {
	ID     string
	ID_2   string
	UserID string
}

func (q *Queries) GetInstallationRevisionTitle(ctx context.Context, arg GetInstallationRevisionTitleParams) (string, error) {
	row := q.db.QueryRow(ctx, getInstallationRevisionTitle, arg.ID, arg.ID_2, arg.UserID)
	var title string
	err := row.Scan(&title)
	return title, err
}

const getInstallationUpdateContext = `-- name: GetInstallationUpdateContext :one
SELECT si.definition_id, sr.title, si.is_default
FROM skill_installations si
JOIN skill_revisions sr ON sr.id = $2 AND sr.definition_id = si.definition_id
WHERE si.id = $1 AND si.user_id = $3
`

type GetInstallationUpdateContextParams struct {
	ID     string
	ID_2   string
	UserID string
}

type GetInstallationUpdateContextRow struct {
	DefinitionID string
	Title        string
	IsDefault    bool
}

func (q *Queries) GetInstallationUpdateContext(ctx context.Context, arg GetInstallationUpdateContextParams) (GetInstallationUpdateContextRow, error) {
	row := q.db.QueryRow(ctx, getInstallationUpdateContext, arg.ID, arg.ID_2, arg.UserID)
	var i GetInstallationUpdateContextRow
	err := row.Scan(&i.DefinitionID, &i.Title, &i.IsDefault)
	return i, err
}

const getSkill = `-- name: GetSkill :one
SELECT si.id, si.user_id, sd.id, sr.id, sr.version, sd.slug, sd.kind,
       sr.title, sr.description, sr.prompt, sr.mode, sr.manifest_json, sd.source, si.enabled,
       sd.repo_url, si.created_at, si.updated_at
FROM skill_installations si
JOIN skill_definitions sd ON sd.id = si.definition_id
JOIN skill_revisions sr ON sr.id = si.current_revision_id
WHERE si.id = $1 AND si.user_id = $2
`

type GetSkillParams struct {
	ID     string
	UserID string
}

type GetSkillRow struct {
	ID           string
	UserID       string
	ID_2         string
	ID_3         string
	Version      int32
	Slug         string
	Kind         string
	Title        string
	Description  string
	Prompt       string
	Mode         string
	ManifestJson string
	Source       string
	Enabled      bool
	RepoUrl      string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetSkill(ctx context.Context, arg GetSkillParams) (GetSkillRow, error) {
	row := q.db.QueryRow(ctx, getSkill, arg.ID, arg.UserID)
	var i GetSkillRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ID_2,
		&i.ID_3,
		&i.Version,
		&i.Slug,
		&i.Kind,
		&i.Title,
		&i.Description,
		&i.Prompt,
		&i.Mode,
		&i.ManifestJson,
		&i.Source,
		&i.Enabled,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillArtifact = `-- name: GetSkillArtifact :one
SELECT id, user_id, definition_id, revision_id, source, file_name, media_type, source_url,
       sha256, size_bytes, entry_path, manifest_path, instructions_path, archive_bytes, created_at
FROM skill_artifacts
WHERE id = $1 AND user_id = $2
`

type GetSkillArtifactParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetSkillArtifact(ctx context.Context, arg GetSkillArtifactParams) (SkillArtifact, error) {
	row := q.db.QueryRow(ctx, getSkillArtifact, arg.ID, arg.UserID)
	var i SkillArtifact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DefinitionID,
		&i.RevisionID,
		&i.Source,
		&i.FileName,
		&i.MediaType,
		&i.SourceUrl,
		&i.Sha256,
		&i.SizeBytes,
		&i.EntryPath,
		&i.ManifestPath,
		&i.InstructionsPath,
		&i.ArchiveBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillArtifactUserId = `-- name: GetSkillArtifactUserId :one
SELECT user_id
FROM skill_artifacts
WHERE id = $1
`

func (q *Queries) GetSkillArtifactUserId(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getSkillArtifactUserId, id)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getSkillDefinition = `-- name: GetSkillDefinition :one
SELECT id, user_id, slug, kind, source, repo_url, created_at, updated_at
FROM skill_definitions
WHERE id = $1 AND user_id = $2
`

type GetSkillDefinitionParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetSkillDefinition(ctx context.Context, arg GetSkillDefinitionParams) (SkillDefinition, error) {
	row := q.db.QueryRow(ctx, getSkillDefinition, arg.ID, arg.UserID)
	var i SkillDefinition
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Kind,
		&i.Source,
		&i.RepoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillImportJob = `-- name: GetSkillImportJob :one
SELECT id, user_id, source, status, artifact_id, definition_id, revision_id, installation_id,
       error_message, request_json, created_at, updated_at, completed_at
FROM skill_import_jobs
WHERE id = $1 AND user_id = $2
`

type GetSkillImportJobParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetSkillImportJob(ctx context.Context, arg GetSkillImportJobParams) (SkillImportJob, error) {
	row := q.db.QueryRow(ctx, getSkillImportJob, arg.ID, arg.UserID)
	var i SkillImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Status,
		&i.ArtifactID,
		&i.DefinitionID,
		&i.RevisionID,
		&i.InstallationID,
		&i.ErrorMessage,
		&i.RequestJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSkillInstallationRecord = `-- name: GetSkillInstallationRecord :one
SELECT si.id, si.user_id, si.definition_id, si.current_revision_id, si.name, si.is_default, si.enabled, si.created_at, si.updated_at,
       sd.id, sd.user_id, sd.slug, sd.kind, sd.source, sd.repo_url, sd.created_at, sd.updated_at,
       sr.id, sr.definition_id, sr.version, sr.title, sr.description, sr.prompt, sr.mode, sr.manifest_json, sr.created_at
FROM skill_installations si
JOIN skill_definitions sd ON sd.id = si.definition_id
JOIN skill_revisions sr ON sr.id = si.current_revision_id
WHERE si.id = $1 AND si.user_id = $2
`

type GetSkillInstallationRecordParams struct {
	ID     string
	UserID string
}

type GetSkillInstallationRecordRow struct {
	ID                string
	UserID            string
	DefinitionID      string
	CurrentRevisionID string
	Name              string
	IsDefault         bool
	Enabled           bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ID_2              string
	UserID_2          string
	Slug              string
	Kind              string
	Source            string
	RepoUrl           string
	CreatedAt_2       pgtype.Timestamptz
	UpdatedAt_2       pgtype.Timestamptz
	ID_3              string
	DefinitionID_2    string
	Version           int32
	Title             string
	Description       string
	Prompt            string
	Mode              string
	ManifestJson      string
	CreatedAt_3       pgtype.Timestamptz
}

func (q *Queries) GetSkillInstallationRecord(ctx context.Context, arg GetSkillInstallationRecordParams) (GetSkillInstallationRecordRow, error) {
	row := q.db.QueryRow(ctx, getSkillInstallationRecord, arg.ID, arg.UserID)
	var i GetSkillInstallationRecordRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DefinitionID,
		&i.CurrentRevisionID,
		&i.Name,
		&i.IsDefault,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.UserID_2,
		&i.Slug,
		&i.Kind,
		&i.Source,
		&i.RepoUrl,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.ID_3,
		&i.DefinitionID_2,
		&i.Version,
		&i.Title,
		&i.Description,
		&i.Prompt,
		&i.Mode,
		&i.ManifestJson,
		&i.CreatedAt_3,
	)
	return i, err
}

const insertSkillArtifactFile = `-- name: InsertSkillArtifactFile :execrows
INSERT INTO skill_artifact_files (
	id, artifact_id, user_id, path, media_type, size_bytes, sha256,
	is_manifest, is_instructions, created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertSkillArtifactFileParams struct {
	ID             string
	ArtifactID     string
	UserID         string
	Path           string
	MediaType      string
	SizeBytes      int64
	Sha256         string
	IsManifest     bool
	IsInstructions bool
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) InsertSkillArtifactFile(ctx context.Context, arg InsertSkillArtifactFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSkillArtifactFile,
		arg.ID,
		arg.ArtifactID,
		arg.UserID,
		arg.Path,
		arg.MediaType,
		arg.SizeBytes,
		arg.Sha256,
		arg.IsManifest,
		arg.IsInstructions,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDefinitionInstallations = `-- name: ListDefinitionInstallations :many
SELECT id, user_id, definition_id, current_revision_id, name, is_default, enabled, created_at, updated_at
FROM skill_installations
WHERE user_id = $1 AND definition_id = $2
ORDER BY is_default DESC, updated_at DESC
`

type ListDefinitionInstallationsParams struct {
	UserID       string
	DefinitionID string
}

type ListDefinitionInstallationsRow struct {
	ID                string
	UserID            string
	DefinitionID      string
	CurrentRevisionID string
	Name              string
	IsDefault         bool
	Enabled           bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ListDefinitionInstallations(ctx context.Context, arg ListDefinitionInstallationsParams) ([]ListDefinitionInstallationsRow, error) {
	rows, err := q.db.Query(ctx, listDefinitionInstallations, arg.UserID, arg.DefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDefinitionInstallationsRow
	for rows.Next() {
		var i ListDefinitionInstallationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DefinitionID,
			&i.CurrentRevisionID,
			&i.Name,
			&i.IsDefault,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillArtifactFiles = `-- name: ListSkillArtifactFiles :many
SELECT saff.id, saff.artifact_id, saff.user_id, saff.path, saff.media_type, saff.size_bytes,
       saff.sha256, saff.is_manifest, saff.is_instructions, saff.created_at
FROM skill_artifact_files saff
JOIN skill_artifacts sa ON sa.id = saff.artifact_id
WHERE saff.artifact_id = $1 AND sa.user_id = $2
ORDER BY saff.path ASC
`

type ListSkillArtifactFilesParams struct {
	ArtifactID string
	UserID     string
}

func (q *Queries) ListSkillArtifactFiles(ctx context.Context, arg ListSkillArtifactFilesParams) ([]SkillArtifactFile, error) {
	rows, err := q.db.Query(ctx, listSkillArtifactFiles, arg.ArtifactID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillArtifactFile
	for rows.Next() {
		var i SkillArtifactFile
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.UserID,
			&i.Path,
			&i.MediaType,
			&i.SizeBytes,
			&i.Sha256,
			&i.IsManifest,
			&i.IsInstructions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillDefinitions = `-- name: ListSkillDefinitions :many
SELECT id, user_id, slug, kind, source, repo_url, created_at, updated_at
FROM skill_definitions
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListSkillDefinitions(ctx context.Context, userID string) ([]SkillDefinition, error) {
	rows, err := q.db.Query(ctx, listSkillDefinitions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillDefinition
	for rows.Next() {
		var i SkillDefinition
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Kind,
			&i.Source,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillImportJobs = `-- name: ListSkillImportJobs :many
SELECT id, user_id, source, status, artifact_id, definition_id, revision_id, installation_id,
       error_message, request_json, created_at, updated_at, completed_at
FROM skill_import_jobs
WHERE user_id = $1
ORDER BY updated_at DESC, created_at DESC
`

func (q *Queries) ListSkillImportJobs(ctx context.Context, userID string) ([]SkillImportJob, error) {
	rows, err := q.db.Query(ctx, listSkillImportJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillImportJob
	for rows.Next() {
		var i SkillImportJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.Status,
			&i.ArtifactID,
			&i.DefinitionID,
			&i.RevisionID,
			&i.InstallationID,
			&i.ErrorMessage,
			&i.RequestJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillInstallations = `-- name: ListSkillInstallations :many
SELECT si.id, si.user_id, si.definition_id, si.current_revision_id, si.name, si.is_default, si.enabled, si.created_at, si.updated_at,
       sd.id, sd.user_id, sd.slug, sd.kind, sd.source, sd.repo_url, sd.created_at, sd.updated_at,
       sr.id, sr.definition_id, sr.version, sr.title, sr.description, sr.prompt, sr.mode, sr.manifest_json, sr.created_at
FROM skill_installations si
JOIN skill_definitions sd ON sd.id = si.definition_id
JOIN skill_revisions sr ON sr.id = si.current_revision_id
WHERE si.user_id = $1
ORDER BY si.updated_at DESC
`

type ListSkillInstallationsRow struct {
	ID                string
	UserID            string
	DefinitionID      string
	CurrentRevisionID string
	Name              string
	IsDefault         bool
	Enabled           bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	ID_2              string
	UserID_2          string
	Slug              string
	Kind              string
	Source            string
	RepoUrl           string
	CreatedAt_2       pgtype.Timestamptz
	UpdatedAt_2       pgtype.Timestamptz
	ID_3              string
	DefinitionID_2    string
	Version           int32
	Title             string
	Description       string
	Prompt            string
	Mode              string
	ManifestJson      string
	CreatedAt_3       pgtype.Timestamptz
}

func (q *Queries) ListSkillInstallations(ctx context.Context, userID string) ([]ListSkillInstallationsRow, error) {
	rows, err := q.db.Query(ctx, listSkillInstallations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillInstallationsRow
	for rows.Next() {
		var i ListSkillInstallationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DefinitionID,
			&i.CurrentRevisionID,
			&i.Name,
			&i.IsDefault,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.UserID_2,
			&i.Slug,
			&i.Kind,
			&i.Source,
			&i.RepoUrl,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.ID_3,
			&i.DefinitionID_2,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.Prompt,
			&i.Mode,
			&i.ManifestJson,
			&i.CreatedAt_3,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillRevisions = `-- name: ListSkillRevisions :many
SELECT sr.id, sr.definition_id, sr.version, sr.title, sr.description, sr.prompt, sr.mode, sr.manifest_json, sr.created_at
FROM skill_revisions sr
JOIN skill_definitions sd ON sd.id = sr.definition_id
WHERE sr.definition_id = $1 AND sd.user_id = $2
ORDER BY sr.version DESC, sr.created_at DESC
`

type ListSkillRevisionsParams struct {
	DefinitionID string
	UserID       string
}

func (q *Queries) ListSkillRevisions(ctx context.Context, arg ListSkillRevisionsParams) ([]SkillRevision, error) {
	rows, err := q.db.Query(ctx, listSkillRevisions, arg.DefinitionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillRevision
	for rows.Next() {
		var i SkillRevision
		if err := rows.Scan(
			&i.ID,
			&i.DefinitionID,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.Prompt,
			&i.Mode,
			&i.ManifestJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT si.id, si.user_id, sd.id, sr.id, sr.version, sd.slug, sd.kind,
       sr.title, sr.description, sr.prompt, sr.mode, sr.manifest_json, sd.source, si.enabled,
       sd.repo_url, si.created_at, si.updated_at
FROM skill_installations si
JOIN skill_definitions sd ON sd.id = si.definition_id
JOIN skill_revisions sr ON sr.id = si.current_revision_id
WHERE si.user_id = $1
ORDER BY si.updated_at DESC
`

type ListSkillsRow struct {
	ID           string
	UserID       string
	ID_2         string
	ID_3         string
	Version      int32
	Slug         string
	Kind         string
	Title        string
	Description  string
	Prompt       string
	Mode         string
	ManifestJson string
	Source       string
	Enabled      bool
	RepoUrl      string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListSkills(ctx context.Context, userID string) ([]ListSkillsRow, error) {
	rows, err := q.db.Query(ctx, listSkills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillsRow
	for rows.Next() {
		var i ListSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ID_2,
			&i.ID_3,
			&i.Version,
			&i.Slug,
			&i.Kind,
			&i.Title,
			&i.Description,
			&i.Prompt,
			&i.Mode,
			&i.ManifestJson,
			&i.Source,
			&i.Enabled,
			&i.RepoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteLatestSkillInstallation = `-- name: PromoteLatestSkillInstallation :execrows
UPDATE skill_installations
SET is_default = TRUE
WHERE id = (
	SELECT id
	FROM skill_installations
	WHERE skill_installations.user_id = $1 AND skill_installations.definition_id = $2
	ORDER BY updated_at DESC, created_at ASC, id ASC
	LIMIT 1
)
`

type PromoteLatestSkillInstallationParams struct {
	UserID       string
	DefinitionID string
}

func (q *Queries) PromoteLatestSkillInstallation(ctx context.Context, arg PromoteLatestSkillInstallationParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteLatestSkillInstallation, arg.UserID, arg.DefinitionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteSkillInstallationDefault = `-- name: PromoteSkillInstallationDefault :execrows
UPDATE skill_installations
SET is_default = TRUE
WHERE id = $1
`

func (q *Queries) PromoteSkillInstallationDefault(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, promoteSkillInstallationDefault, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectPromoteSiblingInstallation = `-- name: SelectPromoteSiblingInstallation :one
SELECT id
FROM skill_installations
WHERE user_id = $1 AND definition_id = $2 AND id <> $3
ORDER BY updated_at DESC, created_at ASC, id ASC
LIMIT 1
`

type SelectPromoteSiblingInstallationParams struct {
	UserID       string
	DefinitionID string
	ID           string
}

func (q *Queries) SelectPromoteSiblingInstallation(ctx context.Context, arg SelectPromoteSiblingInstallationParams) (string, error) {
	row := q.db.QueryRow(ctx, selectPromoteSiblingInstallation, arg.UserID, arg.DefinitionID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateSkillDefinition = `-- name: UpdateSkillDefinition :execrows
UPDATE skill_definitions
SET slug = $2,
    kind = $3,
    source = $4,
    repo_url = $5,
    updated_at = $6
WHERE id = $1 AND user_id = $7
`

type UpdateSkillDefinitionParams struct {
	ID        string
	Slug      string
	Kind      string
	Source    string
	RepoUrl   string
	UpdatedAt pgtype.Timestamptz
	UserID    string
}

func (q *Queries) UpdateSkillDefinition(ctx context.Context, arg UpdateSkillDefinitionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSkillDefinition,
		arg.ID,
		arg.Slug,
		arg.Kind,
		arg.Source,
		arg.RepoUrl,
		arg.UpdatedAt,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSkillImportJob = `-- name: UpdateSkillImportJob :execrows
UPDATE skill_import_jobs
SET source = $2,
    status = $3,
    artifact_id = $4,
    definition_id = $5,
    revision_id = $6,
    installation_id = $7,
    error_message = $8,
    request_json = $9,
    updated_at = $10,
    completed_at = $11
WHERE id = $1 AND user_id = $12
`

type UpdateSkillImportJobParams struct {
	ID             string
	Source         string
	Status         string
	ArtifactID     string
	DefinitionID   string
	RevisionID     string
	InstallationID string
	ErrorMessage   string
	RequestJson    string
	UpdatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	UserID         string
}

func (q *Queries) UpdateSkillImportJob(ctx context.Context, arg UpdateSkillImportJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSkillImportJob,
		arg.ID,
		arg.Source,
		arg.Status,
		arg.ArtifactID,
		arg.DefinitionID,
		arg.RevisionID,
		arg.InstallationID,
		arg.ErrorMessage,
		arg.RequestJson,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSkillInstallation = `-- name: UpdateSkillInstallation :execrows
UPDATE skill_installations si
SET current_revision_id = $2,
    name = $3,
    is_default = $4,
    enabled = $5,
    updated_at = $6
WHERE si.id = $1
  AND si.user_id = $7
  AND EXISTS (
	SELECT 1
	FROM skill_revisions sr
	WHERE sr.id = $2
	  AND sr.definition_id = si.definition_id
  )
`

type UpdateSkillInstallationParams struct {
	ID                string
	CurrentRevisionID string
	Name              string
	IsDefault         bool
	Enabled           bool
	UpdatedAt         pgtype.Timestamptz
	UserID            string
}

func (q *Queries) UpdateSkillInstallation(ctx context.Context, arg UpdateSkillInstallationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSkillInstallation,
		arg.ID,
		arg.CurrentRevisionID,
		arg.Name,
		arg.IsDefault,
		arg.Enabled,
		arg.UpdatedAt,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSkillInstallationRevision = `-- name: UpdateSkillInstallationRevision :execrows
UPDATE skill_installations
SET current_revision_id = $2,
    enabled = $3,
    updated_at = $4
WHERE id = $1 AND user_id = $5
`

type UpdateSkillInstallationRevisionParams struct {
	ID                string
	CurrentRevisionID string
	Enabled           bool
	UpdatedAt         pgtype.Timestamptz
	UserID            string
}

func (q *Queries) UpdateSkillInstallationRevision(ctx context.Context, arg UpdateSkillInstallationRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSkillInstallationRevision,
		arg.ID,
		arg.CurrentRevisionID,
		arg.Enabled,
		arg.UpdatedAt,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
