package gitrepo

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestScanWorkspaceSelectsKeyFilesAndSkipsGeneratedContent(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "README.md", "# Demo\n\nDemo project.")
	writeTestFile(t, root, "package.json", `{"scripts":{"dev":"vite","test":"vitest"}}`)
	writeTestFile(t, root, "src/main.ts", "export function main() { return 'ok'; }\n")
	writeTestFile(t, root, "src/service.ts", "export class Service { run() { return true; } }\n")
	writeTestFile(t, root, "node_modules/pkg/index.js", "ignored")
	writeTestFile(t, root, "dist/bundle.js", "ignored")
	writeTestFile(t, root, "assets/logo.png", "\x89PNG\r\n\x1a\n")
	writeTestFile(t, root, "src/huge.ts", strings.Repeat("x", DefaultMaxFileBytes+1))

	scan, err := ScanWorkspace(root, ScanOptions{})
	if err != nil {
		t.Fatalf("scan workspace: %v", err)
	}

	if !containsPath(scan.KeyFiles, "README.md") {
		t.Fatalf("expected README.md to be selected, got %#v", scan.KeyFiles)
	}
	if !containsPath(scan.KeyFiles, "package.json") {
		t.Fatalf("expected package.json to be selected, got %#v", scan.KeyFiles)
	}
	if !containsPath(scan.KeyFiles, "src/main.ts") {
		t.Fatalf("expected src/main.ts to be selected, got %#v", scan.KeyFiles)
	}
	if containsPath(scan.KeyFiles, "node_modules/pkg/index.js") {
		t.Fatalf("expected node_modules file to be skipped")
	}
	if containsPath(scan.KeyFiles, "dist/bundle.js") {
		t.Fatalf("expected dist file to be skipped")
	}
	if containsPath(scan.KeyFiles, "assets/logo.png") {
		t.Fatalf("expected binary image to be skipped")
	}
	if containsPath(scan.KeyFiles, "src/huge.ts") {
		t.Fatalf("expected oversized file to be skipped")
	}
	if !strings.Contains(scan.TreeMarkdown, "src/") {
		t.Fatalf("expected tree to include src directory, got %s", scan.TreeMarkdown)
	}
}

func TestAnalyzerUsesGeneratorWhenConfigured(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "README.md", "# Demo")
	generator := &fakeGenerator{answer: "# Code Wiki\n\nGenerated by model."}
	analyzer := NewAnalyzerWithGenerator("", generator)

	scan, err := ScanWorkspace(root, ScanOptions{})
	if err != nil {
		t.Fatalf("scan workspace: %v", err)
	}
	markdown, err := analyzer.GenerateCodeWiki(context.Background(), "Generate wiki", scan)
	if err != nil {
		t.Fatalf("generate code wiki: %v", err)
	}
	if markdown != generator.answer {
		t.Fatalf("expected generator answer, got %q", markdown)
	}
	if !strings.Contains(generator.userPrompt, "README.md") {
		t.Fatalf("expected prompt to include key file path, got %s", generator.userPrompt)
	}
}

func TestBuildFallbackCodeWikiIncludesArchitectureAndRunCommands(t *testing.T) {
	scan := WorkspaceScan{
		RepoURL: "https://github.com/acme/demo",
		TreeMarkdown: strings.Join([]string{
			"- README.md",
			"- package.json",
			"- src/",
			"  - main.ts",
		}, "\n"),
		KeyFiles: []FileSummary{
			{Path: "README.md", Language: "markdown", Excerpt: "# Demo"},
			{Path: "package.json", Language: "json", Excerpt: `{"scripts":{"dev":"vite","test":"vitest"}}`},
			{Path: "src/main.ts", Language: "typescript", Excerpt: "export function main() {}"},
		},
		Languages: []string{"TypeScript", "Markdown"},
		RunHints:  []string{"npm run dev", "npm test"},
	}

	markdown := BuildFallbackCodeWiki("Generate a Code Wiki", scan)
	for _, section := range []string{
		"# Code Wiki",
		"## 项目整体架构",
		"## 主要模块职责",
		"## 关键类与函数",
		"## 依赖关系",
		"## 项目运行方式",
		"npm run dev",
	} {
		if !strings.Contains(markdown, section) {
			t.Fatalf("expected markdown to contain %q, got:\n%s", section, markdown)
		}
	}
}

func writeTestFile(t *testing.T, root, path, content string) {
	t.Helper()
	fullPath := filepath.Join(root, path)
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
		t.Fatalf("write file: %v", err)
	}
}

func containsPath(files []FileSummary, path string) bool {
	for _, file := range files {
		if file.Path == path {
			return true
		}
	}
	return false
}

type fakeGenerator struct {
	systemPrompt string
	userPrompt   string
	answer       string
}

func (g *fakeGenerator) Complete(_ context.Context, systemPrompt, userPrompt string) (string, error) {
	g.systemPrompt = systemPrompt
	g.userPrompt = userPrompt
	return g.answer, nil
}
